### ISSUE TITLE
Multi Tenant Blocked In Production 

### ISSUE THREAD

**Issue by drigoalexander** [hieuhani/nuxt-multi-tenancy#15]
Hi, is there any build command on production? 

I've build and deploy it on vercel using ```nuxt build``` , it build perfectly until i open the tenant apps and it returns ```This site can’t provide a secure connection, Error ERR_SSL_PROTOCOL_ERROR```

my nuxt.config.ts 

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  app: {
    pageTransition: { name: "page", mode: "out-in" },
  },
  content: {
    highlight: {
      theme: "github-dark",
    },
    documentDriven: true,
  },
  modules: [
    "@nuxtjs/tailwindcss",
    "@nuxt/content",
    "@hypernym/nuxt-anime",
    "@nuxtjs/google-fonts",
    "nuxt-multi-tenancy",
  ],
  multiTenancy: {
    rootDomains: ["test.local", "test.vercel.app"],
    tenantDynamicRoute: "site",
  },
  anime: {
    provide: true,
    composables: true,
  },
  googleFonts: {
    families: {
      MuseoModerno: true,
      Montserrat: true,
    },
    preload: true,
    preconnect: true,
  },
});

  ```

**Comment by drigoalexander** [comment]
I was thinking for a moment, do i need a domain instead of using vercel in order to achieve the subdomain multi tenant?

**Comment by hieuhani** [comment]
For the first issue ERR_SSL_PROTOCOL_ERROR, I think you might need to wait a bit or use a new browser to check.


> I was thinking for a moment, do i need a domain instead of using vercel in order to achieve the subdomain multi tenant?

In order to support multi-tenancy using subdomain, I think you might need to use a custom domain, check the reference here https://vercel.com/docs/projects/domains/working-with-domains#wildcard-domain

**Comment by drigoalexander** [comment]
Thanks for the help, will try!
