### ISSUE TITLE
Why are links in `jobs.localhost:3000/` pointing to the files in the home directory?

### ISSUE THREAD

**Issue by cybercoder-naj** [hieuhani/nuxt-multi-tenancy#22]
When I am running the application locally, I visit `jobs.localhost:3000/` and I can see that points to `pages/jobs/index.vue` which I think is expected. However, when visiting a link such as `jobs.localhost:3000/some-slug`, I see that this actually renders `pages/[slug].vue`. I don't think that should be the intended behaviour. Am I missing something?

In my opinion, `jobs.localhost:3000/some-slug` should render `pages/jobs/[slug]/index.vue` which I think is failing.

**Comment by hieuhani** [comment]
Please declare the root domain for localhost here https://github.com/hieuhani/nuxt-multi-tenancy/blob/main/playground/nuxt.config.ts#L13C5-L13C16 or you can map `nuxtdev.local` and `jobs.nuxtdev.local` to 127.0.0.1 in the etc/hosts file
