### ISSUE TITLE
Identifier 'tenantRouterOptions' has already been declared

### ISSUE THREAD

**Issue by SVV-team** [hieuhani/nuxt-multi-tenancy#33]
Hi
After some updates (in some packages, nuxt or node), i don`t know,
but in DEV mode after Hot Reload i received error. In production build it works good, but development for now difficult with this error
```
Uncaught SyntaxError: Identifier 'tenantRouterOptions' has already been declared (at router.options.mjs:2:1)
```

<img width="1206" alt="Снимок экрана 2024-12-23 в 23 04 09" src="https://github.com/user-attachments/assets/6012f43d-3bb5-42ef-b6d2-1d324726abd1" />

It`s look like we need to add check if it was already been imported

After page reload its look like 
<img width="1205" alt="Снимок экрана 2024-12-23 в 23 10 25" src="https://github.com/user-attachments/assets/b595d290-3b3b-44e9-b071-f06c93fe8dd0" />

**Versions:**
Nuxt 3.14.1592 with Nitro 2.10.4
Node v22.11.0

**Comment by SVV-team** [comment]
Fixed in fork 
Pull request https://github.com/hieuhani/nuxt-multi-tenancy/pull/34

**Comment by hieuhani** [comment]
Thanks @SVV-team so much.
I merged the pull request.
